### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by andy68man** [pentestpartners/wysedecode#1]
Hello,

I'm trying to compile this with Visual Studio 2015 but I'm getting the error:
Error (active)      argument of type "char *" is incompatible with parameter of type "unsigned char *"  

The issue seems to be with the first variable in the line:
`NFuseDecode(argv[1], strlen(argv[1]), buffer);
`

I'm new to C coding, so have been trying to make a few changes without much success, any chance you could point me in the right direction?

Thanks!

**Comment by jamie-ptp** [comment]
Try this – I haven’t tested as I don’t have test data, but it does seem to compile without errors/warnings. I’ve just cast the parameter to the appropriate pointer type.

// Basic C code to decrypt Wyse password for decoding
// Reverse engineering and C mangulation by David Lodge

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void NFuseDecode(unsigned char *src, int length, unsigned char *dst)
{
   unsigned char a;
   int i;

   length/=2;

   for (i=0; i<length; i++)
   {
      a=src[i_2];
      a-=1;
      a<<=4;
      a+=src[i_2+1];
      a-=0x41;
      dst[i]=a;
   }

   for (i=length; i>=0; i--)
   {
      a=dst[i-1];
      a^=dst[i];
      a^=0xA5;
      dst[i]=a;
   }
   dst[length]='\0';
}

int main(int argc, char **argv)
{
   unsigned char buffer[256];

   NFuseDecode((unsigned char*) argv[1], strlen(argv[1]), buffer);
   printf("%s\n", buffer);

   return 0;
}

**Comment by tautology0** [comment]
There should be no problems with directly casting it as Jamie did - I'll just test this and push a new version to the repo. It looks like Visual C is a lot more anal than gcc is about signedness of characters.

(I've never been able to get Visual C to work, so I always use gcc.)

**Comment by tautology0** [comment]
Right try checking out again and recompiling. I've checked this with gcc -Wall and have had no warnings.

(In the end to stop a cast I just changed the type of char expected by NFuseDecode.)

**Comment by andy68man** [comment]
Excellent, thanks guys!

All compiled well and I've been able to recover my password - saves resetting it on 100's of terminals!
